name: todos_app
description: An example todos app that showcases bloc state management patterns.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^3.1.1
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.7.0
  github_search_repository:
    path: packages/github_search_repository
  google_fonts: ^6.2.1
  intl: ^0.19.0
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  meta: ^1.12.0
  stream_transform: ^2.1.0
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mockingjay: ^0.5.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
