// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBsQm7y9HvCniSyVhsKtlTFqAuUA8rn8',
    appId: '1:719213427078:android:83824145801a2dc0031407',
    messagingSenderId: '719213427078',
    projectId: 'blocxfirebase',
    storageBucket: 'blocxfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzon-VZdr0y5bV5Z4lswAtFyONefppgE4',
    appId: '1:719213427078:ios:2f99cc32b6de2abe031407',
    messagingSenderId: '719213427078',
    projectId: 'blocxfirebase',
    storageBucket: 'blocxfirebase.appspot.com',
    iosClientId:
        '719213427078-1ps6bngrmqlhfglvieve1vl45uhe0cgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.todos-app',
  );
}
